name              'osl-hedgedoc'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Installs/Configures osl-hedgedoc'
issues_url        'https://github.com/osuosl-cookbooks/osl-hedgedoc/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-hedgedoc'
chef_version      '>= 18.0'
version           '1.0.0'

depends           'osl-docker'
depends           'osl-firewall'

supports          'almalinux', '~> 9.0'
supports          'almalinux', '~> 10.0'
